
language: python
python:
    - "pypy"
    - "pypy3"
matrix:
  include:
      - { arch: arm64, python: '3.7' }
      - { python: '3.7', env: }
      - { arch: arm64-graviton2, python: '3.7', virt: lxd, group: edge, dist: xenial}
      - { python: '3.8', env: }
      - { arch: arm64, python: '3.8' }
      - { arch: arm64-graviton2, python: '3.8', virt: lxd, group: edge, dist: xenial}
install:
    - pip install --upgrade pip
    - pip install coverage
    - pip install --upgrade pytest pytest-benchmark

script:
    - |
      if [[ $(bc <<< "$TRAVIS_PYTHON_VERSION >= 3.3") -eq 1 ]]; then
         py.test --doctest-modules multipledispatch
      else
         py.test --doctest-modules --ignore=multipledispatch/tests/test_dispatcher_3only.py multipledispatch
      fi

after_success:
    - |
      if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install coveralls; coveralls ; fi

notifications:
  email: false
